#!/usr/bin/env ruby
require_relative "./completion.rb"

KNOWN_COMMANDS = %w{build config create down events exec help images kill logs pause port ps pull push restart rm run scale start stop top unpause up version}.freeze

puts Completion.new(KNOWN_COMMANDS).matches(ENV["COMP_LINE"])
exit 0
