#!/usr/bin/bash

if [ -f ~/.bash/functions/* ]; then
  for file in ~/.bash/functions/*; do
    source $file
  done
fi

source ~/.bash/aliases
complete -C ~/.bash/completions/project -o default c
complete -C ~/.bash/completions/docker-compose -o default dc
complete -C ~/.bash/completions/docker-compose -o default docker-compose

export PS1='\[\e[0;33m\]\u \[\e[0;32m\]\w\[\e[0;35m\]$(__git_ps1) \n\[\e[0;31m\]\$\[\e[0;37m\] '

export PATH=$HOME/bin:/opt/local/bin:/opt/local/sbin:/sw/bin:$PATH
export EDITOR="subl -w"

### Bash http://blog.macromates.com/2008/working-with-history-in-bash/
export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend

### COLORS
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

# brew setup
eval "$(/opt/homebrew/bin/brew shellenv)"

if type brew &>/dev/null; then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
      [[ -r "$COMPLETION" ]] && source "$COMPLETION"
    done
  fi
fi
