#!/usr/bin/bash

if [ -f ~/.bash/functions/* ]; then
  for file in ~/.bash/functions/*; do
    source $file
  done
fi

source ~/.bash/aliases

source ~/.bash/completions/git
complete -o default -o nospace -F _git_checkout gco
complete -o default -o nospace -F _git_branch gb
complete -o default -o nospace -F _git_commit gc
complete -o default -o nospace -F _git_diff gd
complete -o default -o nospace -F _git_diff gdc
complete -o default -o nospace -F _git_diff gdcs
source ~/.bash/completions/subversion
source ~/.bash/completions/mategem
source ~/.bash/completions/bundler
complete -C ~/.bash/completions/rake -o default rake
complete -C ~/.bash/completions/project -o default c
complete -C ~/.bash/completions/project_go -o default cgo
complete -C ~/.bash/completions/capistrano -o default cap
complete -C ~/.bash/completions/docker-machine -o default dm
complete -C ~/.bash/completions/docker-machine -o default docker-machine
complete -C ~/.bash/completions/docker-compose -o default dc
complete -C ~/.bash/completions/docker-compose -o default docker-compose

export PS1='\[\e[0;33m\]\u \[\e[0;32m\]\w\[\e[0;35m\]$(__git_ps1) \[\e[0;36m\]$(~/.rvm/bin/rvm-prompt) \n\[\e[0;31m\]\$\[\e[0;37m\] '

export PATH=$HOME/bin:/opt/local/bin:/opt/local/sbin:/sw/bin:$PATH
export PATH=$PATH:/usr/local/mysql/bin
export EDITOR="subl"
export SVN_EDITOR=$EDITOR

### Bash http://blog.macromates.com/2008/working-with-history-in-bash/
export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend

### COLORS
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

### MySql
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH

### Redis
export REDIS_PATH=/usr/local/bin/redis-server

### Elastic
export ELASTIC_EXECUTABLE_PATH=/usr/local/bin/elasticsearch

### ChefDK
export PATH=$HOME/.chefdk/gem/ruby/2.1.0/bin:/opt/chefdk/bin:$PATH

### RabbitMQ
export PATH=$PATH:/usr/local/sbin

### google-cloud-sdk
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc'

###GO
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
