#!/usr/bin/bash

if [ -f ~/.bash/functions/* ]; then
  for file in ~/.bash/functions/*; do
    source $file
  done
fi

source ~/.bash/aliases

source ~/.bash/completions/git
complete -o default -o nospace -F _git_checkout gco
complete -o default -o nospace -F _git_branch gb
complete -o default -o nospace -F _git_commit gc
complete -o default -o nospace -F _git_diff gd
complete -o default -o nospace -F _git_diff gdc
complete -o default -o nospace -F _git_diff gdcs
source ~/.bash/completions/subversion
source ~/.bash/completions/mategem
source ~/.bash/completions/bundler
complete -C ~/.bash/completions/rake -o default rake
complete -C ~/.bash/completions/project -o default c
complete -C ~/.bash/completions/project -o default cm
complete -C ~/.bash/completions/capistrano -o default cap

export PS1='\[\e[0;33m\]\u \[\e[0;32m\]\w\[\e[0;35m\]$(__git_ps1) \[\e[0;36m\]$(~/.rvm/bin/rvm-prompt) \n\[\e[0;31m\]\$\[\e[0;37m\] '

export PATH=$HOME/bin:/opt/local/bin:/opt/local/sbin:/sw/bin:$PATH
export PATH=$PATH:/usr/local/mysql/bin/
export EDITOR="subl -n -w"
export SVN_EDITOR=$EDITOR

### Bash http://blog.macromates.com/2008/working-with-history-in-bash/
export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend

### COLORS
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

### MySql
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH
